export interface ProductModel {
  id?: string;
  productId?: string | number;
  name: string;
  sku?: string;
  productCode?: string;
  barcode?: string;
  categoryId: number;
  categoryName?: string;
  brand?: string;
  unit?: string;
  unitOfMeasure?: string;
  costPrice?: number;
  sellingPrice?: number;
  unitPrice?: number;
  currentStock: number;
  quantityInStock?: number;
  reorderLevel: number;
  reorderQuantity?: number;
  tax?: number;
  status?: boolean;
  description?: string;
  createdOn?: Date | string;
  createdAt?: Date | string;
  createdBy?: string;
  updatedOn?: Date | string;
  updatedAt?: Date | string;
  updatedBy?: string;
  deletedOn?: Date | string;
  deletedBy?: string;
}
